#!/bin/sh

sed -i -e 's|/etc/savevar|#removed line|g' /etc/rc.local

[ -f "/etc/variable.file" ] || {
	/etc/rcfix &
}

echo 'NETCREATE="'"0"'"' > /etc/variable.file
echo 'NETSIERRA="'"0"'"' >> /etc/variable.file
echo 'SIERRACTIVE="'"0"'"' >> /etc/variable.file
echo 'QMIWWAN="'"0"'"' >> /etc/variable.file
echo 'KEEPALIVE="'"0"'"' >> /etc/variable.file
echo 'RBDELAY="'"1"'"' >> /etc/variable.file

uci delete cbi_file.Version
uci set cbi_file.Version=version
uci set cbi_file.Version.ver="Falcon 3.0-11"


local AUTH=$(uci get cbi_file.Network.auth)
if [ -z $AUTH ]; then
	uci set cbi_file.Network.auth="0"
fi
local ALIVE=$(uci get cbi_file.Network.alive)
if [ -z $ALIVE ]; then
	uci set cbi_file.Network.alive="0"
fi

local PTIME=$(uci get cbi_file.Network.pingtime)
if [ -z $PTIME ]; then
	uci set cbi_file.Network.pingtime="2"
	uci set cbi_file.Network.pingwait="10"
	uci set cbi_file.Network.pingnum="1"
	uci set cbi_file.Network.pingserv1="8.8.8.8"
fi

local DELAY=$(uci get cbi_file.Network.delay)
if [ -z $DELAY ]; then
	uci set cbi_file.Network.delay="5"
else
	if [ $DELAY = 60 ]; then
		uci set cbi_file.Network.delay="5"
	fi
fi

echo 'TOGGLE="'"0"'"' > /tmp/toggle.file
uci set cbi_file.Version.log="0"
uci set cbi_file.Version.getsig="0"

local ACTIVE=$(uci get cbi_file.ModSched.active)
if [ -z $ACTIVE ]; then
	uci delete cbi_file.ModSched
	uci set cbi_file.ModSched=modsched
	uci set cbi_file.ModSched.active="0"
fi
ACTIVE=$(uci get cbi_file.WifiSched.active)
if [ -z $ACTIVE ]; then
	uci delete cbi_file.WifiSched
	uci set cbi_file.WifiSched=wifisched
	uci set cbi_file.WifiSched.active="0"
fi

uci commit cbi_file

source /etc/openwrt_release
rm -f /etc/openwrt_release
DISTRIB_DESCRIPTION="$(uci get cbi_file.Version.ver)"
echo 'DISTRIB_ID="'"$DISTRIB_ID"'"' >> /etc/openwrt_release
echo 'DISTRIB_RELEASE="'"$DISTRIB_RELEASE"'"' >> /etc/openwrt_release
echo 'DISTRIB_REVISION="'"$DISTRIB_REVISION"'"' >> /etc/openwrt_release
echo 'DISTRIB_CODENAME="'"$DISTRIB_CODENAME"'"' >> /etc/openwrt_release
echo 'DISTRIB_TARGET="'"$DISTRIB_TARGET"'"' >> /etc/openwrt_release
echo 'DISTRIB_DESCRIPTION="'"$DISTRIB_DESCRIPTION"'"' >> /etc/openwrt_release

BWB=$(uci get monitor.bandwidth.bdown)
if [ -z $BWB ]; then
	uci set monitor.bandwidth.bdown="0"
	uci set monitor.bandwidth.bup="0"
	uci set monitor.bandwidth.btotal="0"
fi
uci set monitor.bandwidth.basedown=$(uci get monitor.bandwidth.bdown)
uci set monitor.bandwidth.baseup=$(uci get monitor.bandwidth.bup)
uci set monitor.bandwidth.basetotal=$(uci get monitor.bandwidth.btotal)

uci commit monitor
/etc/wrtbwmon update /tmp/usage.db peak

/etc/gpiomodel
/etc/monitor
/etc/modpwr

echo "-" > /tmp/status.file
echo "-" >> /tmp/status.file
echo "-" >> /tmp/status.file
echo "-" >> /tmp/status.file
echo "No Modem Present" >> /tmp/status.file
echo "-" >> /tmp/status.file
echo "-" >> /tmp/status.file
echo "-" >> /tmp/status.file
echo "-" >> /tmp/status.file
echo "-" >> /tmp/status.file
echo "-" >> /tmp/status.file
echo "-" >> /tmp/status.file
echo "-" >> /tmp/status.file
echo "-" >> /tmp/status.file
echo "-" >> /tmp/status.file
echo "-" >> /tmp/status.file
echo "-" >> /tmp/status.file
echo "-" >> /tmp/status.file
echo "-" >> /tmp/status.file
echo " " >> /tmp/status.file
echo " " >> /tmp/status.file
echo "-" >> /tmp/status.file
echo "-" >> /tmp/status.file
echo "-" >> /tmp/status.file

echo "0" > /tmp/bootend.file


